preparing a readme file
ivan0dyatlyukkk/book-worm pull request #14
Opened 2023-10-01 18:08 UTC by ivan0dyatlyukkk

2023-10-05 12:58 UTC, andrii-hoienko requested changes
GJ! Let`s improve your solution

2023-10-05 12:58 UTC, andrii-hoienko commented on README.md
> +The video instructions for usage you can watch here: link-for-the-loom-video
Where is the link? Or am I missing something?

2023-10-05 12:58 UTC, andrii-hoienko commented on README.md
> +   If you don't want to come up with an idea of data for the testing requests, and you don't want to type lots of similar requests again and again, you can use the prepared [collection for Postman](#
Add something about Contributing

2023-10-10 14:04 UTC, ivan0dyatlyukkk commented on README.md
> +The video instructions for usage you can watch here: link-for-the-loom-video
Sorry, I haven't prepared a loom video yet, and I created the readme for checking my main concept

2023-10-16 15:24 UTC, vovasalyha approved these changes

2023-10-17 12:16 UTC, merged