implemented new features into BookController
ivan0dyatlyukkk/book-worm pull request #3
Opened 2023-09-05 10:32 UTC by ivan0dyatlyukkk

added dtos classes, set up mapstruct and mapper, implemented new features into the BookController, BookService and BookRepository

2023-09-05 13:48 UTC, IhorKalaur approved these changes
Looks Good

2023-09-05 15:34 UTC, vovasalyha requested changes
GJ! Left few minor suggestions.

2023-09-05 15:34 UTC, vovasalyha commented on src/main/java/org/diatliuk/bookstore/repository/impl/BookRepositoryImpl.java
> +            Query<Book> getBookById = session.createQuery(hql, Book.class);
You can use `find` method instead of manual query.

2023-09-05 15:34 UTC, vovasalyha commented on src/main/java/org/diatliuk/bookstore/service/impl/BookServiceImpl.java
> +    public List<BookDto> findAll() {
Be consistent in naming, if you called one service method with `get` pattern, try to use it in other methods too.

2023-09-05 15:34 UTC, vovasalyha commented on src/main/java/org/diatliuk/bookstore/service/impl/BookServiceImpl.java
> +        if (optionalBook.isPresent()) {
Use `orElseThrow` to make your code cleaner.

2023-09-06 14:13 UTC, vovasalyha approved these changes
GJ

2023-09-06 14:13 UTC, vovasalyha commented on src/main/java/org/diatliuk/bookstore/repository/BookRepository.java
> +    Optional<Book> findBookById(Long id);
```suggestion
    Optional<Book> findById(Long id);
```

2023-09-06 14:18 UTC, merged